# -*- coding: utf-8 -*-
"""Meu primeiro algoritmo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ub4yssbLCEAl3E6qO15QtNJ-RMLCADW
"""

for i in range(2):
    print(f"\n--- Operação {i + 1} de 2 ---")



    #Tratamento de exceção para evitar erros na digitação
    try:
        #Uso do float() para permitir números inteiros e decimais
        num1 = float(input('Digite o primeiro número: '))
        num2 = float(input('Digite o segundo número: '))
    except ValueError:
        #Mensagem ao usuário
        print("Erro: Entrada inválida! Por favor, digite apenas números.")
        continue


    #Processamento das operações
    soma = num1 + num2
    sub = num1 - num2
    mult = num1 * num2


    #Exibição dos resultados com identificação clara de cada operação
    print("\nSoma:", soma)
    print("Subtração:", sub)
    print("Multiplicação:", mult)


    #Tratamento de erro na divisão por zero
    try:
        div = num1 / num2
        print("Divisão:", div)
    except ZeroDivisionError:
        print("Divisão: Não é possível dividir um número por zero!")